language: python
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.nvm
  - node_modules
  - wger/node_modules
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
env:
- TEST_MOBILE=True  DB=postgresql TRAVIS_NODE_VERSION="4"
- TEST_MOBILE=True  DB=sqlite     TRAVIS_NODE_VERSION="4"
- TEST_MOBILE=False DB=postgresql TRAVIS_NODE_VERSION="4"
- TEST_MOBILE=False DB=sqlite     TRAVIS_NODE_VERSION="4"
install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | METHOD=script
  bash
- . $HOME/.nvm/nvm.sh
- nvm install $TRAVIS_NODE_VERSION
- nvm use $TRAVIS_NODE_VERSION
- pip install -r requirements_devel.txt
- npm install
- if [[ "$DB" = "postgresql" ]]; then pip install psycopg2; fi
- if [[ "$DB" = "sqlite" ]]; then invoke create_settings; fi
- if [[ "$DB" = "postgresql" ]]; then invoke create_settings --database-type postgresql;
  fi
before_script:
- if [[ "$DB" = "postgresq" ]]; then psql -c 'DROP DATABASE IF EXISTS test_wger;'
  -U postgres; fi
- if [[ "$DB" = "postgresql" ]]; then psql -c 'CREATE DATABASE test_wger;' -U postgres;
  fi
script:
- pep8 wger
- gulp lint
- coverage run --source='.' ./manage.py test
- coverage report
notifications:
  slack:
    secure: TMNkmZkoCve8807/gx7eEkdpLWvYbB+N4FzfN4PVcl15dBRYv9ebgOamMLNytXWg4+cJdElRt8lVyx+cGFyx8chjTrYwtxoacUKKyHArEE0BsZXWpF0OOUcBhV4ofOvFaqF4nedanTacv5NfY3c3NcWm/Rktg2LT5UddofKw6ToROEPMVzf5733y4XIi7oNriKf87BWvn/+wYTcly5Ii1n892vEBQePBGa6lv5EZjOSG8oS45FGQEq/4vwhHA1R4cmuasQwsPOPI+EHYdLUsnmTZY2Ei2/aqX1zNfrqNmO60cWrZhGeSLhPcQwASeWHk7MUuurNpK8WRzGft2S4A5miSJpun7sALYi6gz8thSfGCXVaRNV8PXumHISWn8cgl/v8iTpaxkVktPKfMTz1CI/841DFS19gvQVZ4+/qgrpvP6Bi5Bn+y07VqdFVJogPaaBomKN30JuiO9kkr/qvYvA+KcAKfTs3gFeRd+ubrLuWk8baKR09NPrB/EMg4E6ZrSRDRKDQqc2+QVSJVc0L3V+s1Oo59TVLKxjg8HAc9aF9h3gTDRqficrcdMyXx0+TrFZ59+Sr9J2vNcDY4z3kiB99UVpl5XVVRcDibdfXxQ0S35YHvXitN4fjTjB/AT+NmikxjVPYCBwXMsIezHV14jrhAQ3IldRaN5Nw1QWfzb0o=
