# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-01 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20171201_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealconsumed',
            name='ingredient',
            field=models.TextField(
                default='something',
                help_text='What was actually consumed by a user',
                max_length=2000,
                verbose_name='Ingredient Consumed'),
        ),
    ]
