# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20171201_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealconsumed',
            name='meal',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient_consumed',
            field=models.TextField(
                blank=True,
                default='something',
                help_text='What was actually consumed by a user',
                max_length=2000,
                null=True,
                verbose_name='Ingredient Consumed'),
        ),
        migrations.DeleteModel(
            name='MealConsumed',
        ),
    ]
