# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20171201_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealConsumed',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('ingredient_consumed',
                 models.TextField(
                     blank=True,
                     default='something',
                     help_text='What was actually consumed by a user',
                     max_length=2000,
                     null=True,
                     verbose_name='Ingredient Consumed')),
                ('meal',
                 models.ForeignKey(
                     editable=False,
                     on_delete=django.db.models.deletion.CASCADE,
                     to='nutrition.Meal',
                     verbose_name='Nutrition plan')),
            ],
        ),
    ]
