# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-02 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_mealconsumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='ingredient_consumed',
        ),
    ]
