# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-02 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_remove_mealitem_ingredient_consumed'),
        ('nutrition', '0002_auto_20171123_1632'),
    ]

    operations = [
    ]
