# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-07 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_merge'),
        ('nutrition', '0003_auto_20171205_1518'),
    ]

    operations = [
    ]
