# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-14 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_auto_20171209_1043'),
        ('nutrition', '0009_merge'),
    ]

    operations = [
    ]
