# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-23 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20160303_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='license',
            name='full_name',
            field=models.CharField(
                help_text='If a license has been localized, e.g. the Creative Commons licenses for the different countries, add them as separate entries here.',
                max_length=60,
                verbose_name='Full name'),
        ),
    ]
