# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-19 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_daysofweek_period_type'),
        ('core', '0012_author'),
    ]

    operations = [
    ]
