# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-19 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='name'),
        ),
    ]
