# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_workoutsession_workout_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='cycle',
            field=models.CharField(choices=[('Microcycle', 'Microcycle - up to 1 week'), ('Mesocycle', 'Mesocycle - 2 to 6 weeks'), ('Macrocycle', 'Macrocycle - up to 12 months')], default='Microcycle', max_length=10),
        ),
    ]
